name: Create Pull Request
on:
  push:
    branches:
      - "develop"
      - "master"
jobs:
  generate-build-number:
    runs-on: ubuntu-latest
    outputs:
      build_number: AVU-develop/${{ steps.buildnumber.outputs.build_number }}
    steps:
      # - name: Generate build number
      #   id: buildnumber
      #   uses: einaregilsson/build-number@v2
      #   with:
      #     token: ${{secrets.github_token}}
      #     prefix: AVU-develop/
      - uses: actions/checkout@v2
      # - uses: peterjgrainger/action-create-branch@v1.0.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     branch: AVU-develop/${{ steps.buildnumber.outputs.build_number }}
      # - uses: actions/checkout@v2
      #   with:
      #     ref: AVU-develop/${{ steps.buildnumber.outputs.build_number }}
      - name: Version Patch
        run: |
          git config --global user.email "validation-lib@pfcinc.us"
          git config --global user.name "validation-lib"
          npm version patch
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto Version Update
          committer: Auto Version Update Action <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "[AVU] Auto Version Update"
          body: |
            This Pull request is created by AVR, it will be auto merged and should not be updated or reopened.
          labels: valet:merge, Automated-pr
          assignees: HassanNiazi
          reviewers: HassanNiazi
          team-reviewers: owners, maintainers
          draft: false
          branch: AVU-dev-2
          branch-suffix: timestamp
          request-to-parent: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
